### PR TITLE
Updated ooi_get_location.

### PR DESCRIPTION
**Pull request by IanTBlack**
Added elif statement for dropping paired CTD datasets for VELPT requests if the user sets the drop_paired parameter to TRUE.

### CODE REVIEW

**Comment by IanTBlack** [comment]
Found more problems. Waiting until all resolved to push.

**Comment by IanTBlack** [comment]
Just kidding. The patch works okay.

**Review by cwingard — CHANGES_REQUESTED** [review]
Remove the charityware from the license and switch the license to the MIT License (https://opensource.org/licenses/MIT).

**Review by IanTBlack — COMMENTED** [review]
Removed charityware note.

**Pull request merged**
